# -*- coding: utf-8 -*-
"""Komandalar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-3Hxm7xuroC9_-wpreDUigYoZIRsyT3G

# Komandalar
# sana 06.02.2026
# Muallif: Lutfiyev Doniyor
"""

print('''SalomDunyo''')

age = input("Yoshingni kiriting: ")
print(age)

x = 10
name = "Doniyor"
pi = 3.14

age = 2

if age >= 18:
    print("Voyaga yetgan")
elif age == 17:
    print("Deyarli yetgan")
else:
    print("Voyaga yetmagan")

for i in range(1):
    print(i)

x = 1
while x <= 5:
    print(x)
    x += 1

def salom():
    print("Salom Doniyor")

salom()

def kvadrat(n):
    return n * n

print(kvadrat(8))

numbers = [10, 20, 30, 40]
print(numbers[0])
numbers.append(50)

student = {
    "name": "Ali",
    "age": 20
}

print(student["name"])
print(student["age"])

try:
    x = int(input("Son kiriting: "))
    print(x)
except:
    print("Xato! Son kiriting")

# Bu izoh
print("Hello")

f = open("test.txt", "w")
f.write("Salom")
f.close()

name = input("Ismingni yoz: ")

print("salom")

len("doni")

max(7, 5, 2)

sum([7, 2, 1])

pow(2, 1)

for i in range(4):

  print(i)

range(5)

range(2, 6)

x = range(0, 10, 2)
print(x)

x = float(5)
print(x)

print(type(1
           ))

name = input("ismingizni yozing: ")

student = dict(name="ali", age=20)
print(student)

sorted([6,5,4,2,8,1,9])

print("hello Python")

name = input("ismingizni yozing: ")

x_str = input("biror son kiriting: ")
y_str = input("ikkinchi son kiriting: ")

try:
    x = int(x_str)
    y = int(y_str)
    print(f"Yig'indi: {x + y}")
except ValueError:
    print("Iltimos, faqat son kiriting.")

print(7+8)

print('"Nexia", "Tiko",\'damas\' ko\'ganlar qilinglar havas ')

print(5**4) # darajaga ko'tarish uchun  2ta **  cha ishlatiladi

print(22/4)  # agar bitta bo'lish belgisi ishlatilsa sonni butun va
# qoldiq qismini ham yozadi
print(22//4) # bunda faqat butun qismi yoziladi
print("22 ni 4 ga bo'lganda qancha qoldiq", 22%4) # % bu qoldiqni
# topadi

print("tomonlari 125 ga teng kvadratning yuzi ", 125*125, "ga",
"peremetri ", 125*4, "ga teng") # qavsda yozganda vergul bilan
#  yozsa kod buzilmaydi
# qator taylaganda # yana bir bor qo'yiladi

print("diametri 12 ga teng doiraning yuzi", 6**2*3.14,
      "ga teng")

print("Katetlari 6 sm va 7sm\n bo'lgan to'g'ri burchakli\n"
 "uchburchakning gipotenuzasi\n", (6**2+7**2)**(1/2), "sm", "ga teng")

ism = "Abdulloh"
yosh = 25
print(ism)
print(yosh)

ism = "Abdulloh"
ism="Muhammad"
print(ism)
print(ism)
3=="k"
print(3)
Doni__7 = "lutfiyev"
print(Doni__7)
#class = "h"
#print(class) mumkin emas chunki kalit so'z

radius = 5
pi = 3.14159
aylana_yuzi = pi * radius**2
print("Radiusi" , radius, "ga teng aylananing yuzi=", aylana_yuzi)

# 5-dars string
ism = "Ahad"
familiya = 'Qayum'
ism_sharif = f"{ism} {familiya}"
print(ism_sharif)

ism = 'Ahad'
familiya = 'Qayum'
print(ism + familiya)

ism = 'Ahad'
familiya = 'Qayum'
print(ism + ' ' + familiya) # ikki o'zgaruvchi orasiga bo'sh joy qo'shamiz

print("I REMEMBER RECEIVING A LETTER FROM THE AMERICAN publisher Harper\n"
"Collins that said that: “reading The Alchemist was like getting up at \n"
"dawn and seeing the sun rise while the rest of the world still slept.” I \n"
"went outside, looked up at the sky, and thought to myself: “So, the \n"
"book is going to be published in English!” At the time, I was \n"
"struggling to establish myself as a writer and to follow my path \n"
"despite all the voices telling me it was impossible. ".upper())

ism = "Lutfiyev Donoyor"
print(ism)
Ism = 'Ahad'
Familiya = 'Qayum'
print(Ism+' '+Familiya)
ism_sharif=f"{Ism} {Familiya}"
print(ism_sharif)

print('Hello \n'
'world!')

import requests
import json
from IPython.display import Image, display

# Giphy API kalitingizni shu yerga kiriting.
# Giphy Developer veb-saytidan (developers.giphy.com) bepul kalit olishingiz mumkin.
GIPHY_API_KEY = "YOUR_GIPHY_API_KEY"  # <<< O'z API kalitingizni bu yerga joylashtiring

def search_giphy_gif(query):
    if not GIPHY_API_KEY or GIPHY_API_KEY == "YOUR_GIPHY_API_KEY":
        print("Iltimos, Giphy API kalitingizni kiriting. Kalit olish uchun: developers.giphy.com")
        return

    url = f"https://api.giphy.com/v1/gifs/search"
    params = {
        "api_key": GIPHY_API_KEY,
        "q": query,
        "limit": 1, # Faqat bitta GIF qaytarsin
        "rating": "g" # Har qanday yoshga mos keladigan GIFlar
    }

    try:
        response = requests.get(url, params=params)
        response.raise_for_status() # HTTP xatolarini tekshirish
        data = response.json()

        if data["data"]:
            gif_url = data["data"][0]["images"]["original"]["url"]
            print(f"Sizning so'rovingiz bo'yicha GIF: {gif_url}")
            # Colabda GIFni bevosita ko'rsatishga urinish
            display(Image(url=gif_url))
        else:
            print(f"'{query}' so'rovi bo'yicha GIF topilmadi.")
    except requests.exceptions.RequestException as e:
        print(f"APIga ulanishda xatolik yuz berdi: {e}")
    except json.JSONDecodeError:
        print("API javobini qayta ishlashda xatolik yuz berdi. Javob to'g'ri formatda emas.")
    except KeyError:
        print("API javobining kutilgan formatida xatolik. GIF URL topilmadi.")


# Foydalanuvchidan so'rovni olish
user_input = input("Qanday GIF topishni istaysiz? ")
search_giphy_gif(user_input)

ism = 'Ahad'
familiya = 'Qayum'
ism_sharif = f"{ism} {familiya}"
print(ism_sharif.upper())

ism = 'Ahad'
familiya = 'Qayum'
ism_sharif = f"{ism} {familiya}"
print(ism_sharif
      .upper())

meva = "     olma     "
print("Men "
 + meva.lstrip() +
      " yaxshi ko'raman")
print("Men " +
      meva.rstrip()
       + " yaxshi ko'raman")
print("Men "
      + meva.strip() #fgcjhgfgfh
      + " yaxshi ko'raman")#hgfhgfhgf
print("Men " #jhgjhgjhg
      + meva +#hjgjhgjhgjkgjhgjhgjhgjhgjhgkj
        #gfjhgjhhkjhlkjhkjhkjhkjh
      #hgjhgjhgjhgjhgjhgjgjhgjhgjhgjg
      " yaxshi ko'raman")

meva = "     olma     "
print("Men " + meva.lstrip() +#" yaxshi ko'raman")
print("Men " + meva.rstrip() + " yaxshi ko'raman")
print("Men " + meva.strip() + " yaxshi ko'raman")
print("Men " + meva + " yaxshi ko'raman")

meva = "     olma     "
print("Men " + meva.lstrip() + " yaxshi ko'raman")
print("Men " + meva.rstrip() + " yaxshi ko'raman")
print("Men " + meva.strip() + " yaxshi ko'raman")
print("Men " + meva + " yaxshi ko'raman")

ism = input("Ismingiz nima? ")
print("Assalom alaykum, " + ism)
print (input( "familiyangiz nima   "  + "asalomu alekum"           ))

ism = input("Ismingiz nima? ")
print("Assalom alaykum, " + ism)
print(input('ismingiz '),)

ism = input("Ismingiz nima?\n>>>")
 # Foydalanuvchi ismini yangi qatordan kiritadi
print("Assalom alaykum, " + ism.title())

# 5-dars Amaliyot
#1
kocha = "Bog'bon"
mahalla = "sog'bon"
tuman = "Bodonmzor"
viloyat= "Samarqand"
print(kocha+" "+"kochasi,"+
      " "+ mahalla+"\n" "mahallasi,"+" "+tuman+
      " "+"tumani,"+" \n"+viloyat+" "+"viloyati")

#2
kocha = input("kochangizni nomini kiriting: ")
mahalla = input("mahallangiz nomi: ")
tuman = input("tumaningiz nomi: ")
viloyat = input("viloyatingizni kiriting: ")
print("\n"+kocha+" "+"kochasi,"+
      " "+ mahalla+"\n" "mahallasi,"+" "+tuman+
      " "+"tumani,"+" \n"+viloyat+" "+"viloyati")
manzil = f"{kocha} {mahalla} {tuman} {viloyat}"
print(manzil.title())

#06 SONLAR
son = int(input("istalgan son kiriting "))
type(son)
print(son,"ning kvadrati", son**2,"ga teng""\n"
,son,"ning kubi",son**3, "ga teng")

yoshi = int(input("Yoshingiz nechida? "))
t_yil = 2026-yoshi
print("siz ", t_yil, "yilda tug'ulgansiz")

son1 = int(input("1-sonni kiriting: "))
son2 = int(input("2-sonni kiriting: "))
yigindi =  son1+son2
ayirma = son1-son2
kopaytma = son1*son2
bolinma = son1/son2
print("ikki sonning yigindisi ",yigindi,
      "ga teng\nayirmasi esa ", ayirma,
     "ga teng \nko'paytmasi esa ",kopaytma,
      "ga teng \nbo'linmasi esa ",bolinma,
      "ga teng")
print(son1,"+",son2,"=",yigindi)

# jabobi
#1
x = int(input("Istalgan son kiriting:\n>>>"))
print(x, " ning kvadrati ", x**2, " ga teng")
print(x, " ning kubi ", x**3, " ga teng")

#2
yosh = int(input("Yoshingiz nechida? \n>>>"))
t_yil = 2020-yosh
print("Siz ", t_yil, " da tug'ilgansiz")

# 3 title
a = float(input("Birinchi sonni kiriting: "))
b = float(input("Ikkinchi sonni kiriting: "))
print(f"{a}+{b}=", a+b)
print(f"{a}-{b}=", a-b)
print(f"{a}x{b}=", a*b)
print(f"{a}/{b}=", a/b)

# 07 List (ro'yxat)
mevalar = ['olma', 'anjir', 'shaftoli', "o'rik"]
# mevalar ro'yxati (matnlar)
narhlar = [12000, 18000, 10900, 22000]
# narhlar ro'yxati (sonlar)
sonlar = ['bir', 'ikki', 3, 4, 5]
# sonlar va matnlar aralash ro'yxat
ismlar = [] # bo'sh ro'yxat

mevalar = ['olma', 'anjir', 'shaftoli', "o'rik"] # mevalar ro'yxati (matnlar)
print("Birinchi meva: ", mevalar[0])
print("Ikkinchi meva: ", mevalar[1])

mevalar = ['olma', 'anjir', 'shaftoli', "o'rik"] # mevalar ro'yxati (matnlar)
print("Birinchi meva: ", mevalar[0].title())
print("Ikkinchi meva: ", mevalar[1].upper())

narhlar = [12000, 18000, 10900, 22000]
print(narhlar[2] + narhlar[3])

car_models = ['Toyota', 'GM', 'Volvo', 'BMW', 'Hyundai', 'Kia', 'Volkswagen']
print(car_models[-1]) # Listning eng oxirgi elementiga -1 bilan murojat qilamiz

narhlar = [12000, 18000, 10900, 22000]
narhlar[0] = 13000 # 1-qiymatni 13000 ga o'zgartiramiz
narhlar[2] = 11000 # 3-qiymatni 11000 ga o'zgartiramiz
narhlar[3] = narhlar[3]+2000 # 4-qiymatga 2000 qo'shamiz
print(narhlar)

mevalar = ['olma', 'anjir', 'shaftoli', "o'rik"]
mevalar.append("tarvuz") # mevalar ga tarvuz qo'shamiz
print(mevalar)

cars = [] # bo'sh ro'yxat yaratamiz
cars.append('Lacetti') # ro'yxatga Lacetti mashinasini qo'shamiz
cars.append('Nexia 3') # ro'yxatga Nexia 3 mashinasini qo'shamiz
cars.append('Cobalt')  # ro'yxatga Cobalt  mashinasini qo'shamiz
print(cars)

cars = ['Lacetti', 'Nexia 3', 'Cobalt']
cars.insert(0, 'Malibu') # 1-o'ringa yangi qiymat qo'shamiz
print(cars)

cars.insert(2, 'Damas') # 3-o'ringa yangi qiymat qo'shamiz
print(cars)

mevalar = ['olma', 'anjir', 'shaftoli', "o'rik", 'anor']
del mevalar[1] # 2-element (anjir) ni o'chirib tashlaymiz
print(mevalar)

mevalar = ['olma', 'anjir', 'shaftoli', "o'rik", 'anor']
mevalar.remove('shaftoli') # Ro'yxatdan shaftolini o'chirdik
print(mevalar)

hayvonlar = ['it', 'mushuk', 'sigir', 'qo\'y', 'quyon', 'mushuk']
hayvonlar.remove("mushuk") # Ro'yxatda 2 ta mushuk bor, ulardan birinchisi o'chadi
print(hayvonlar)

bozorlik = ["yog'", 'un', 'piyoz', 'banan', "go'sht"]
mahsulot = bozorlik.pop(3) # Ro'yxatdan banan ni sug'urib olamiz
mahsulot = bozorlik.pop(2)
print("Men " + mahsulot + " sotib oldim")
print("Olinmagan mahsulotlar: ", bozorlik)

# 7-dars amaliyot
ismlar = ["Jo'rabek,","Og'abek,","Suxrob"]
print("Salom",ismlar[0],"Bugun choyxona bormi?\n"
,ismlar[1],"Choyxonaga boramizmi?")

sonlar = [2,3,8,4,6,-9,0.3,8.3]

sonlar[1]=8
print(sonlar[0]+sonlar[1])

t_shaxslar = ["Al Xorazmiy", "Abu Ali Ibn Sino"]
z_shaxslar = ["Ilon Mask","Donolt Tranp"]
a = t_shaxslar.pop(0)
print(t_shaxslar)
print(a)
b = z_shaxslar.pop(1)
print(a,"buyuk shaxs")
print(b,"amerika prizidenti")

friends = []
friends.append("Doniyor")
friends.append("Aslam")
friends.append("Akram")
friends.append("Norqul")
friends.append("Ilhom")
friends.remove("Akram")
print(friends)
friends.insert(0,"Tog'om")
friends.insert(3,"Bobom")
friends.insert(6,"Onem")
print(friends)
a = friends.pop(0)
b = friends.pop(0)
c = friends.pop(0)
friends.append("bobo")
mehmonlar=[a,b,c]
print(mehmonlar)
print(friends)
d = friends.pop(2)
print(d)

cars = ['bmw','mercedes benz', 'volvo', 'general motors', 'tesla', 'audi']
cars.sort()
print(cars)

cars = ['Bmw','mercedes benz', 'volvo', 'gm', 'tesla', 'audi']
cars.sort()
print(cars)

cars = ['bmw','mercedes benz', 'volvo', 'general motors', 'tesla', 'audi']
cars.sort(reverse=True)
print(cars)

mehmonlar = ['Odil', 'Hamid', 'Temur', 'Avazbek', 'Farruh', 'Shamsiddin']
print("sorted() qaytargan ro'yxat:", sorted(mehmonlar))
print("Asl ro'yxat o'zgarmas qoldi:", mehmonlar)
print(sorted(mehmonlar, reverse=True))

list(range(1,11,2))

narhlar = [12000, 22500, 23456, 9800, 5600, 9934, 32874]
arzon = min(narhlar)
qimmat = max(narhlar)
jami = sum(narhlar)
print("Eng arzon narh ", arzon, ". Eng qimmati ", qimmat, ". Jami: ", jami)

cars = ['bmw','mercedes benz', 'volvo', 'general motors', 'tesla', 'audi']
my_cars = cars[0:3] # 0-indeskdan boshlab 3 ta element ajratib olamiz
print(my_cars)
print(cars)
print(cars[:4]) # Ro'yxat boshidan 4-gacha kesadi (0,1,2,3)
print(cars[2:]) # 2-elementdan boshlab ro'yxat oxirigacha kesib oladi

sonlar = [1, 2, 3, 4, 5] # donlar degan ro'yxat yaratamiz
sonlar2 = sonlar # sonlar2 degan ro'yxatni sonlar ga tenglaymiz
sonlar2.append(6) # sonlar2 ga 6 sonini qo'shamiz
sonlar2.append(7) # sonlar2 ga 7 sonini qo'shamiz
print("Bu sonlar ro'yxati:", sonlar)
print("Bu sonlar2 ro'yxati:", sonlar2)

sonlar = [1, 2, 3, 4, 5] # donlar degan ro'yxat yaratamiz
sonlar2 = sonlar[:] # [:] ro'yxatni to'liq ko'chirib oladi
sonlar2.append(6) # sonlar2 ga 6 sonini qo'shamiz
sonlar2.append(7) # sonlar2 ga 7 sonini qo'shamiz
print("Bu sonlar ro'yxati:", sonlar)
print("Bu sonlar2 ro'yxati:", sonlar2)

# Tuples-O'zgarmas ro'yxat
tomonlar = (20, 30, 55.2)
print(tomonlar)

# Tuple ichidagi elementlarga huddi ro'yxat
# elementlariga murojat qilingani kabi murojat
# qilinaveradi:
toys = ('bus','car','bear','dino','snake','lizard')
print(toys[0])
print(toys[-1])
print(toys[2:5])

# Keling Tuple ichidagi biror
# elementning qiymatini o'zgartirib ko'ramiz:
toys = ('bus','car','bear','dino','snake','lizard')
toys[3] = 'dragon'

toys = ('bus','car','bear','dino','snake','lizard') # o'zgarmas ro'yxat
toys = list(toys) # o'zgarmas ro'yxatni oddiy ro'yxatga (List) aylantiramiz
# Ro'yxatga o'zgartirishlar kiritamiz
toys.append('dragon')
toys.remove('bus')
toys[1] = 'mcqueen'
toys = tuple(toys) # Ro'yxatni qaytadan o'zgarmas ro'yxatga (Tuple) aylantiramiz
print(toys)

# 8-dars amaliyot
davlatlar = ["Tojikiston","O'zbesiston", "Qirg'iston","Turmaniston",]
print('1#'), print(davlatlar) #1
print() #2
print(len(davlatlar)) #3
print() #4
print(sorted(davlatlar))#5
print()#6
print(sorted(davlatlar,reverse=True))#7
print()#8
print(davlatlar)#9
print()#10
davlatlar.reverse()#
print()#11
print(davlatlar)#12
davlatlar.sort()#
print()#13
print(davlatlar)#14
print( )#15
print(sorted(davlatlar,reverse=True))#16

sonlar=list(range(120,1200,2))
print(sonlar)
a = sum(sonlar)
print("Summa=",a)
b = max(sonlar)-min(sonlar)
print("max-min=",b)
print("elementlar soni",len(sonlar))
print("boshidagi 20 ta",sonlar[:20])
print("oxiridan 20 ta ",sonlar[-20:])
print ("o'rtasidan 20ta", sonlar[110:130])

taomlar = []
taomlar.append("palov")
taomlar.append("Shashlik")
taomlar.append("manti")
taomlar.append("shurva")
taomlar.append("somsa")
nonushta = taomlar[:]
nonushta.pop(0)
nonushta.pop(1)
nonushta.append("non")
nonushta.append("choy")
print(nonushta)
print(taomlar)
nonushta = list(nonushta)
nonushta[0] = "qaymoq va non"
print(nonushta)

# 9-dars amaliyot
Qarindoshlar = ["Akmal","Akobir","Zarif","Azam","Mirzo"]
for qarindosh in Qarindoshlar:
  print(f"Asalom {qarindosh} aka nag'mi shumo")
print("kod 5 marta takrorlandi")

toq_sonlar = list(range(11,100,2))
for kub in toq_sonlar:
  print(kub,"ning kubi",kub**3,"ga teng")

kinolar =[]
print("5 ta sevimli kinoigiz nomini kiriting")
for n in range(1,6):
  kinolar.append(input(f"{n}-kino "))
print(kinolar)

kinolar =[]
print("5 ta sevimli kinongiz nomini kiriting")
for a in range(5):
  kinolar.append(input())
print(kinolar)

print("Bugun necha kishi bilan suhbat qildingiz?")
suhbatdoshlar_soni = int(input())
for s in range(suhbatdoshlar_soni):
  input(f"{s+1}-suhbat qilgan odamingiz kim edi: ")
  print()

# javobi
n_people = int(input("Bugun necha kishi bn suhbat qildingiz?>>>"))
ismlar = []
for n in range(n_people):
    ismlar.append(input(f"{n+1}-suhbat qilgan odamingiz kim edi: "))
print(ismlar)

ism = input('Ismingiz nima?\n>>>') # Foydalanuvchi ismini so'raymiz
if ism.lower() != 'ali': # Agar ism Aliga teng bo'lmasa ...
    print(f"Uzr, {ism.title()} biz Alini kutayapmiz.") # quyidagi xabar chiqadi
else:
    print("Salom, Ali")

# 10 dars amaliyot
cars = ['toyota', 'mazda', 'hyundai', 'gm', 'kia']
for car in cars:
   if car == 'gm':
    print(car.upper())
   else:
    print(car.title())

# 10 dars amaliyot
cars = ['toyota', 'mazda', 'hyundai', 'gm', 'kia']
for car in cars:
   if car != 'gm':
    print(car.upper())
   else:
    print(car.title())

login=input('login kiriting ')
if login == "admin":
  print("Xush kelibsiz, Admin. Foydalanuvchilar ro'yxatini ko'rasizmi?")
else:
  print("Xush kelibsiz ",login)

son1 = input("iltimos son kiriting: ")
son2 = input("iltimos son kiriting: ")
if son1 == son2:
  print("sonlar teng")
else:
  print("sonlar teng emas")

son =int(input("istalgan son kiriting: "))
if son >= 0:
  print("Son musbat son")
else:
  print("manfiy son")

son =int(input("istalgan son kiriting: "))
if son >= 0:
  print(son**(1/2))
else:
  print("Musbat son kiriting")

# 11-dars amaliyot
listdagi_juft = list(range(0,999999,2))
foydalanuvchi_k_s = int(input("juft son kiriting "))
if foydalanuvchi_k_s in listdagi_juft:
  print("Rahmat")
else:
  print("juft son kiriting")

son = float(input("Juft son kiriting: "))
if son%2:
    print('Bu son juft emas.')
else:
    print("Rahmat!")

son1 = int(input("1-sonni kiriting: "))
son2 = int(input("2-sonni kiriting: "))
if son1>son2:
  print(f"{son1}>{son2}")
elif son1==son2:
  print(f"{son1}={son2}")
else:
  print(f"{son1}<{son2}")

mahsulotlar = ["olma","anor","kivi","banan",
               'nok',"gilos","anjir","behi",
               "tarvuz","qovun"]
yangi_savat = []
for n in range(int(input("kamida 5 ta mahsulot kiriting"
"\nnechta mahsulot kiritishni xohlaysiz "))):
  yangi_savat.append(input(f"{n+1}-mahsulotni kiriting: "))
for savat in yangi_savat:
   if savat in mahsulotlar:
    print(f"do'konimizda {savat} bor")
   else:
    print(f"do'konimizda {savat} yoq")

"""
25/11/2020
Dasturlash asoslari
#11-dars: if-elif-else
Muallif: Anvar Narzullaev
Web sahifa: https://python.sariq.dev
"""

mahsulotlar = ['un', "yog'", "sovun", 'tuxum', 'piyoz',
               'kartoshka', 'olma', 'banan', 'uzum', 'qovun']


savat = []
for n in range(5):
    savat.append(input(f"Savatga {n+1}-mahsulotni qo'shing: "))


for mahsulot in savat:
    if mahsulot in mahsulotlar:
        print(f"Do'konimizda {mahsulot} bor")
    else:
        print(f"Do'konimizda {mahsulot} yo'q")

# 11-dars BIR NECHTA SHARTLARNI TEKSHIRISH
kun = input("Bugun nima kun?")
harorat = float(input("Havo harorati qanday?"))
if kun.lower()=='yakshanba' and harorat>=30:
    print("Cho'milgani ketdik!")
elif kun.lower()=='yakshanba' and harorat<30:
    print("Uyda dam olamiz!")

a=1
a==1

narh = 15000 # mijoz 15000 so'mga taom oldi.
choy = 2 # mijoz choy ham oldi
salat = 2 # mijoz salat olmadi

if choy and salat: # agar mijoz choy ham salat ham olgan bo'lsa
    narh = narh + 10000 # narhga 10000 so'm qo'shamiz
elif choy or salat: # agar choy yoki salat olgan bo'lsa
    narh = narh + 5000 # narhga 5000 so'm qo'shamiz

print(f"Jami {narh} so'm") # yakuniy narhni chiqaramiz
# bu yerda 2 desak ham narx 2 marta hisoblanmaydi
# 2=1 10000=1

menu = ['osh','qazonkabob','shashlik','norin','somsa']
'manti' in menu # menu da manti bormi?

menu = ['osh','qazonkabob','shashlik','norin','somsa']
buyurtmalar = ["osh","somsa","manti", "shashlik"]

for taom in buyurtmalar:
    if taom in menu:
        print(f"Menuda {taom} bor")
    else:
        print(f"Kechirasiz, menuda {taom} yo'q")

sonlar = [1,2,3]
if sonlar:
    print("Ro'yxatda sonlar bor")
else:
    print("Ro'yxatda sonlar yoq")

menu = ['osh','qazonkabob','shashlik','norin','somsa']
buyurtmalar = ["osh","somsa","manti", "shashlik"]

if buyurtmalar: # ro'yxatda biror element bo'lsa bu ifoda TRUE qaytaradi
    for taom in buyurtmalar:
        if taom in menu:
            print(f"Menuda {taom} bor")
        else:
            print(f"Kechirasiz, menuda {taom} yo'q")
else: # agar ro'yxat bo'sh bo'lsa
    print("Savatchangiz bo'sh!")

j_son = int(input("iltimos juft son kiriting: "))
if j_son%2==0:
  print("Rahmat")
else:
  print("juft son kiriting")

son = float(input("Juft son kiriting: "))
if son%2:
    print('Bu son juft emas.')
else:
    print("Rahmat!")

mahsulotlar = ["olma","anor","kivi","banan",
               'nok',"gilos","anjir","behi",
               "tarvuz","qovun"]
savats = []
for a in range(1,6):
  savats.append(input(f"{a}-mahsulotni kiriting: "))
bor_mahsulotlar = []
mavjud_emas = []
for savat in savats:
  if savat in mahsulotlar:
    bor_mahsulotlar.append(savat)
  else:
    mavjud_emas.append(savat)
if mavjud_emas:
  print("Quyidagi mahsulotlar do'konimizda yo'q: .....")
  print(mavjud_emas)
else:
    print("Siz so'ragan barcha mahsulotlar do'konimizda bor")

foydalanuvchilar = ["doni","lutfiyev","aslam","samandar","amir"]
login = input("Yangi login tanlang: ")
if login in foydalanuvchilar:
    print("Login band, yangi login tanlang!")
else:
    print("Xush kelibsiz foydalanuvchi!")

"""
25/11/2020
Dasturlash asoslari
#11-dars: if-elif-else
Muallif: Anvar Narzullaev
Web sahifa: https://python.sariq.dev
"""

users = ['alisher','aziza','yasina','umar']

login = input("Yangi login tanlang: ")

if login in users:
    print('Login band, yangi login tanlang!')
else:
    print(f"Xush kelibsiz, {login.title()}!")

k_son = float(input("Biror butun son kiriting:" ))
for son in range(2,11):
   if not k_son%son:
    print(f"{k_son} soni {son} ga qoldiqsiz bo'linadi")

# 12 dars amaliyot

son = float(input("Juft son kiriting: "))
if not son%2==0:
    print("Bu son juft emas.")
else:
    print("Rahmat!")

yosh = int(input("Yoshingiz nechida?"))

if yosh<=4 or yosh>=60:
    narh = 0
elif yosh < 18:
    narh = 10000
else:
    narh = 20000
print(f"Chipta {narh} so'm")

x = float(input("Birinchi sonni kiriting: "))
y = float(input("Ikkinchi sonni kiriting: "))
if x==y:
    print(f"{x}={y}")
elif x<y:
    print(f"{x}<{y}")
else:
    print(f"{x}>{y}")

mahsulotlar = ['un', "yog'", "sovun", 'tuxum', 'piyoz',
               'kartoshka', 'olma', 'banan', 'uzum', 'qovun']
savat = []

for n in range(5):
    savat.append(input(f"Savatga {n+1}-mahsulotni qo'shing: "))
if savat:
    for mahsulot in savat:
        if mahsulot in mahsulotlar:
            print(f"Do'konimizda {mahsulot} bor")
        else:
            print(f"Do'konimizda {mahsulot} yo'q")
else:
    print("Savatingiz bo'sh")

"""
27/11/2020
Dasturlash asoslari
#12-dars: Xatolar
Muallif: Anvar Narzullaev
Web sahifa: https://python.sariq.dev
"""

mahsulotlar = ['un', "yog'", "sovun", 'tuxum', 'piyoz',
               'kartoshka', 'olma', 'banan', 'uzum', 'qovun']


savat = []
for n in range(5):
    savat.append(input(f"Savatga {n+1}-mahsulotni qo'shing: "))

bor_mahsulotlar = []
mavjud_emas = []
for mahsulot in savat:
    if mahsulot in mahsulotlar:
        bor_mahsulotlar.append(mahsulot)
    else:
        mavjud_emas.append(mahsulot)

if mavjud_emas:
  print("Do'konimizda quyidagi mahsulotlar yo'q:")
  for mahsulot in mavjud_emas:
    print(mahsulot)
else:
  print("Siz so'ragan barcha mahsulotlar do'konimizda bor")

"""
27/11/2020
Dasturlash asoslari
#12-dars: Xatolar
Muallif: Anvar Narzullaev
Web sahifa: https://python.sariq.dev
"""

users = ['alisher1983','aziza','yasina', 'umar']

login = input("Yangi login tanlang: ")

if login in users:
    print('Login band, yangi login tanalng!')
else:
    print("Xush kelibsiz!")

